version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: backend-challenge-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: catalogdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
